
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/36064/.conda/envs/cocos_env/Library/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:30 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
...
